### ISSUE TITLE
FileLock is not working on FreeBSD

### ISSUE THREAD

**Issue by moskrc** [SmileyChris/django-mailer-2#17]
Hi Chris!

This is a great library. I found the problem. I moved from linode.com (ubuntu / linux) on FreeBSD. And the library is no longer working. I commented out the code to work with LockFile and it solved my problem. But it's bad ... Prompt me what to do with FreeBSD?

```
>>> from lockfile import FileLock, AlreadyLocked, LockTimeout
>>> lock = FileLock('/tmp/123.lock')
>>> lock.acquire(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lockfile.py", line 261, in acquire
    raise LockTimeout
lockfile.LockTimeout
>>> 
```

Help me please.

Thanks!

**Comment by SmileyChris** [comment]
I'm not sure exactly where your problem lies. It sounds like it could be permissions related.

I would suggest doing some searches or testing around writing to/deleting from the tmp directory and see what you come up with. Please report back with any findings.
