### ISSUE TITLE
Postgresql and send_all results in "unexpected EOF on client connection" messages.

### ISSUE THREAD

**Issue by houdinihound** [SmileyChris/django-mailer-2#2]
This issue only affects people using postgresql.  Basically send_all does not explicitly close the db connection when finished, so postgresql logs the above error.  The problem arises when one regularly runs the command (in my case via cron every minute).  Every minute an error is logged to the postgresql logs about the connection being dropped on the client side.

Note that django-mailer works completely as expected - the patch created by carl.j.meyer and available at the link below just stops cluttering up the pg log files.

Patch and more info on the problem available here:
http://code.google.com/p/django-mailer/issues/detail?id=15

I have applied this simple patch and can confirm that it resolves this issue for me.  

Am raising it here as it might be a good idea to apply this patch for the folks using postgresql.

**Comment by SmileyChris** [comment]
Fixed in 8a9f1c8. Thanks
