### ISSUE TITLE
Django 1.4 and timezone support.

### ISSUE THREAD

**Issue by PSyton** [SmileyChris/django-mailer-2#20]
Application operate with not aware times.
with USE_TZ = True django_mailer generate many "DateTimeField received a naive datetime" runtime warnings.

**Comment by SmileyChris** [comment]
On latest master?

**Comment by PSyton** [comment]
From pypi
I've created patch
https://github.com/PSyton/django-mailer-2/commit/476ad03e150634de1bca95b8ff8fb54681635362

**Comment by PSyton** [comment]
Added pull request.
